[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/tailwind",
    "projects/tailwind-types",
    "projects/tailwind-ast",
    "projects/tailwind-parser",
    "projects/tailwind-resolve",
    "projects/tailwind-css",
]
exclude = [
    "projects/.DS_Store",
]


[profile.dev]
opt-level = 1
incremental = true

[profile.release]
lto = true
panic = "abort"
